global_ekf_node:
  ros__parameters:

    use_sim_time: true 
    frequency: 30.0 

    two_d_mode: true

    world_frame: map # This wil create the odom => map transform
    base_link_frame: base_link

    # Sensor config: [x_pos,    y_pos,     z_pos,
    #                 roll,     pitch,     yaw,
    #                 x_vel,    y_vel,     z_vel,
    #                 roll_vel, pitch_vel, yaw_vel,
    #                 x_accel,  y_accel,   z_accel]

    # Wheel encoder config
    odom0: /diff_drive_controller/odom
    odom0_config: [false, false, false,     
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    # IMU config
    imu0: /imu/data
    imu0_config: [false, false, false,     
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    # Navsat odom from navsat_transform_node
    odom1: /navsat_transform/navsat_odometry
    odom1_config: [false, false, false,     
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]


navsat_transform_node:
  ros__parameters:

    use_sim_time: true 
    frequency: 5.0
