<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="base_length" value="1.5"/>
  <xacro:property name="base_width" value="1.0"/>
  <xacro:property name="base_height" value="0.5"/>
  <xacro:property name="wheel_radius" value="0.2"/>
  <xacro:property name="wheel_width" value="0.1"/>
  <xacro:property name="wheel_suspension" value="0.05"/>
  <xacro:property name="wheel_spacing" value="0.02"/>
  <xacro:property name="caster_radius" value="0.07"/>

  <!-- Links -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <material name="SaxionGreen">
        <color rgba="0 0.612 0.510 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
    <xacro:box_inertia m="30.0" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <link name="base_footprint"/>

  <!--                                         -->
  <!-- Start of camera on top of smart_diffbot -->
  <!--                                         -->

  <xacro:property name="camera_width" value="0.0"/>
  <xacro:property name="camera_depth" value="0.0"/>
  <xacro:property name="camera_height" value="0.0"/>
  <xacro:property name="lens_radius" value="0.0"/>
  <xacro:property name="lens_length" value="0.0"/>

  <!-- Camera body -->
  <link name="camera_body_link">
    <visual>
      <geometry>
        <!-- Insert camera body shape -->
      </geometry>
        <!-- Insert camera body color -->
      </visual>
    <collision>
      <geometry>
        <!-- Insert camera body shape -->
      </geometry>
    </collision>
        <!-- Insert camera body inertia -->
    </link>

  <!-- Camera lens -->
  <link name="camera_lens_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <!-- Insert camera lens shape -->
      </geometry>
      <!-- Insert camera lens color -->
    </visual>
    <collision>
      <geometry>
        <!-- Insert camera lens shape -->
      </geometry>
    </collision>
        <!-- Insert camera lens inertia -->
  </link>

  <!-- Joint connecting camera lens to camera body -->
  <joint name="camera_lens_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="camera_body_link"/>
    <child link="camera_lens_link"/>
  </joint>

  <!-- Joint connecting camera body to robot base_link -->
  <joint name="camera_body_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_body_link"/>
  </joint>

  <!--                                       -->
  <!-- End of camera on top of smart_diffbot -->
  <!--                                       -->


  <!-- Other sensor links (not visualized) -->
  <link name="imu_link"/>
  <link name="navsat_link"/>
  <link name="camera_link"/>

  <!-- Wheel links -->
  <xacro:wheel name="left_wheel" width="${wheel_width}" radius="${wheel_radius}" mass="1.0" color="white"/>
  <xacro:wheel name="right_wheel" width="${wheel_width}" radius="${wheel_radius}" mass="1.0" color="white"/>

  <link name="caster">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.5" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <!-- Joints -->
  <joint name="footprint_joint" type="fixed">
      <origin xyz="0 0 ${- base_height/2.0 - wheel_radius + wheel_suspension}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="base_footprint"/>
  </joint>

  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="imu_link"/>
  </joint>

  <joint name="navsat_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="navsat_link"/>
  </joint>

  <joint name="camera_sensor_joint" type="fixed">
    <origin xyz="${lens_length/2.0 + 0.1} 0 0" rpy="0 0 0"/>
    <parent link="camera_lens_link"/>
    <child link="camera_link"/>
  </joint>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="${-base_length/4.0} ${base_width/2.0 + wheel_width/2.0 + wheel_spacing} ${-base_height/2.0 + wheel_suspension}" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="${-base_length/4.0} -${base_width/2.0 + wheel_width/2.0 + wheel_spacing} ${-base_height/2.0 + wheel_suspension}" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="${base_length/3.0} 0 ${-base_height/2.0 + wheel_suspension - wheel_radius + caster_radius}" rpy="0 0 0"/>
  </joint>

</robot>